"""create community author

Revision ID: 0f297436eeb6
Revises: 1a40bd941f83
Create Date: 2025-03-05 16:06:00.841075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f297436eeb6'
down_revision: Union[str, None] = '1a40bd941f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'community', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'community', type_='foreignkey')
    # op.drop_column('community', 'creator_id')
    # ### end Alembic commands ###
    pass
