"""Added user gallery

Revision ID: 4094fca6b5b0
Revises: c02c97409c7d
Create Date: 2025-04-20 20:05:31.950284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4094fca6b5b0'
down_revision: Union[str, None] = 'c02c97409c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_gallery_id'), 'user_gallery', ['id'], unique=False)
    op.create_index(op.f('ix_user_gallery_user_id'), 'user_gallery', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_gallery_user_id'), table_name='user_gallery')
    op.drop_index(op.f('ix_user_gallery_id'), table_name='user_gallery')
    op.drop_table('user_gallery')
    # ### end Alembic commands ###
