"""re-update likes-post relationship

Revision ID: 8e64a3a698ca
Revises: 690b58b6f0cc
Create Date: 2025-02-23 16:56:02.311570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e64a3a698ca'
down_revision: Union[str, None] = '690b58b6f0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
