"""23.12.2024 Added relationship in Comment

Revision ID: b6caf9eba21c
Revises: 43bbef33b3f8
Create Date: 2024-12-23 14:46:11.673427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6caf9eba21c'
down_revision: Union[str, None] = '43bbef33b3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
