"""Added avatar

Revision ID: c02c97409c7d
Revises: d75cdd1f1f76
Create Date: 2025-04-15 17:39:55.465102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02c97409c7d'
down_revision: Union[str, None] = 'd75cdd1f1f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    op.alter_column('community', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('post', sa.Column('community_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'community', ['community_id'], ['id'])
    op.add_column('user', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_url')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'community_id')
    op.alter_column('community', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
