"""23.12.2024 Updated relationship in Comment

Revision ID: eae1af1c4bbc
Revises: bdce1e1d06fc
Create Date: 2024-12-23 16:08:42.175888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae1af1c4bbc'
down_revision: Union[str, None] = 'bdce1e1d06fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
