"""Add date_of_birth to User

Revision ID: efaf89cea3f3
Revises: eae1af1c4bbc
Create Date: 2024-12-26 15:27:26.424073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efaf89cea3f3'
down_revision: Union[str, None] = 'eae1af1c4bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'date_of_birth')
    # ### end Alembic commands ###
