"""added message model

Revision ID: 06007552ff93
Revises: 32e938ff9e25
Create Date: 2025-06-29 18:47:41.008892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06007552ff93'
down_revision: Union[str, Sequence[str], None] = '32e938ff9e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_recipient_id'), 'chat_message', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_chat_message_sender_id'), 'chat_message', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_sender_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_recipient_id'), table_name='chat_message')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
