"""Create categories

Revision ID: 53be368939a2
Revises: efaf89cea3f3
Create Date: 2025-02-08 19:40:56.041073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53be368939a2'
down_revision: Union[str, None] = 'efaf89cea3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('((|R|Rb|bR|F|FR|B|fr|Rf|BR|rF|RB|Fr|Br|u|rf|b|br|RF|f|rB|U|rb|r|fR)\'[^\\n\'\\\\]*(?:\\\\.[^\\n\'\\\\]*)*\'|(|R|Rb|bR|F|FR|B|fr|Rf|BR|rF|RB|Fr|Br|u|rf|b|br|RF|f|rB|U|rb|r|fR)"[^\\n"\\\\]*(?:\\\\.[^\\n"\\\\]*)*")', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_categories',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_categories')
    op.drop_table('category')
    # ### end Alembic commands ###
