"""update likes-post relationship

Revision ID: 690b58b6f0cc
Revises: 8741a06ab1ea
Create Date: 2025-02-23 16:53:03.786136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690b58b6f0cc'
down_revision: Union[str, None] = '8741a06ab1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
