"""23.12.2024 Updated relationship in Comment

Revision ID: bdce1e1d06fc
Revises: 986608c53963
Create Date: 2024-12-23 16:06:06.502336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdce1e1d06fc'
down_revision: Union[str, None] = '986608c53963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
