"""update likes-comment relationship

Revision ID: c9c87aec0c8c
Revises: 8e64a3a698ca
Create Date: 2025-02-23 17:03:54.001634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c87aec0c8c'
down_revision: Union[str, None] = '8e64a3a698ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
