"""Added comment images

Revision ID: fa8921c5a3ef
Revises: 4094fca6b5b0
Create Date: 2025-04-22 17:36:09.349172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8921c5a3ef'
down_revision: Union[str, None] = '4094fca6b5b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_images_comment_id'), 'comment_images', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_images_id'), 'comment_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_images_id'), table_name='comment_images')
    op.drop_index(op.f('ix_comment_images_comment_id'), table_name='comment_images')
    op.drop_table('comment_images')
    # ### end Alembic commands ###
